# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161207_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crayfish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Cpudata',
        ),
    ]
